---
- name: Pull code-server image
  become_user: "{{ username }}"
  containers.podman.podman_image:
    name: "docker.io/codercom/code-server:latest"
  register: podman_pull
  until: podman_pull is not failed
  retries: 5
  delay: 15

- name: Create code-server directories
  become_user: "{{ username }}"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  loop:
    - "/home/{{ username }}/code-server-config"
    - "/home/{{ username }}/code-server-project"

- name: Ensure code-server container is running
  become_user: "{{ username }}"
  containers.podman.podman_container:
    name: code-server
    image: codercom/code-server:latest
    state: started
    ports:
      - "8080:8080"
    env:
      DOCKER_USER: "{{ username }}"
      PASSWORD: "{{ admin_password }}"
    volumes:
      - "/home/{{ username }}/code-server-config:/home/coder/.config:Z"
      - "/home/{{ username }}/code-server-project:/home/coder/project:Z"
  when:
    - dns_type is defined
    - dns_type == "none"

- name: Ensure code-server container is running with DNS
  become_user: "{{ username }}"
  containers.podman.podman_container:
    name: code-server
    image: codercom/code-server:latest
    state: started
    ports:
      - "8080:8080"
    volumes:
      - "/home/{{ username }}/code-server-config:/home/coder/.config:Z"
      - "/home/{{ username }}/code-server-project:/home/coder/project:Z"
      - "/home/{{ username }}/{{ student }}.{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}:/home/coder/certs:Z"
    env:
      DOCKER_USER: "{{ username }}"
      PASSWORD: "{{ admin_password }}"
    command:
      - "--cert"
      - "/home/coder/certs/cert.pem"
      - "--cert-key"
      - "/home/coder/certs/privkey.pem"
  when:
    - dns_type is defined
    - dns_type != "none"