---
- name: Ensure code-server configuration directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.config/code-server"
    state: directory
    mode: '0755'

- name: Ensure code-server config.yaml configuration is set | DNS off
  ansible.builtin.copy:
    content: |
      bind-addr: 0.0.0.0:{{ code_server_port | default('8123') }}
      password: "{{ admin_password }}"
    dest: "/home/{{ username }}/.config/code-server/config.yaml"
    mode: '0644'
  when:
    - dns_type is defined
    - dns_type == "none"
  register: code_server_config
  until: code_server_config is not failed

- name: Ensure code-server config.yaml configuration is set | DNS on
  when:
    - dns_type is defined
    - dns_type == "aws"
  ansible.builtin.copy:
    content: |
      bind-addr: 0.0.0.0:{{ code_server_port | default('8123') }}
      cert: "/home/{{ username }}/{{ student }}.{{ ec2_name_prefix | lower | default('unknown') }}.{{ workshop_dns_zone | default('example.com') }}/cert.pem"
      cert-key: "/home/{{ username }}/{{ student }}.{{ ec2_name_prefix | lower | default('unknown') }}.{{ workshop_dns_zone | default('example.com') }}/privkey.pem"
      password: "{{ admin_password }}"
    dest: "/home/{{ username }}/.config/code-server/config.yaml"
    mode: '0644'

- name: Download code-server RPM
  ansible.builtin.get_url:
    url: "https://github.com/coder/code-server/releases/download/v4.17.1/code-server-4.17.1-amd64.rpm"
    dest: "/tmp/code-server.rpm"
    mode: '0755'
  when: not pre_build|bool

- name: Install code-server
  ansible.builtin.yum:
    name: "/tmp/code-server.rpm"
    state: present
    disable_gpg_check: true
  when: not pre_build|bool

- name: Enable and start code-server for student
  ansible.builtin.systemd:
    name: "code-server@{{ username }}"
    enabled: true
    state: started

# source: https://vscode.readthedocs.io/en/latest/getstarted/settings/
- name: Ensure custom facts directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/.local/share/code-server/User/"
    recurse: true
    state: directory
    owner: "{{ username }}"
  when: not pre_build|bool

- name: Apply code server defaults
  ansible.builtin.template:
    src: settings.json
    dest: "/home/{{ username }}/.local/share/code-server/User/settings.json"
    owner: "{{ username }}"
    group: "{{ username }}"
  when: not pre_build|bool

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/{{ username }}/.local/share/code-server/extensions/
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  when: not pre_build|bool

- name: Download files for vscode
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: /home/{{ username }}/.local/share/code-server/extensions/
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - https://github.com/ansible/workshops/raw/devel/files/bierner.markdown-preview-github-styles-0.1.6.vsix
    - https://github.com/ansible/workshops/raw/devel/files/hnw.vscode-auto-open-markdown-preview-0.0.4.vsix
    - https://github.com/ansible/workshops/raw/devel/files/redhat.ansible-0.4.5.vsix
  register: download_extension
  until: download_extension is not failed
  retries: 5
  when: not pre_build|bool

- name: Install ansible and markdown extensions
  become_user: "{{ username }}"
  ansible.builtin.command: "/bin/code-server --install-extension /home/{{ username }}/.local/share/code-server/extensions/{{ item }}"
  loop:
    - bierner.markdown-preview-github-styles-0.1.6.vsix
    - hnw.vscode-auto-open-markdown-preview-0.0.4.vsix
    - redhat.ansible-0.4.5.vsix
  ignore_errors: true
  register: install_extension
  until: install_extension is not failed
  retries: 5
  when: not pre_build|bool
