---
- name: Print out pre_build var and dns_type
  ansible.builtin.debug:
    msg:
      - pre_build: "{{ pre_build | default('none set') }}"
      - dns_type: "{{ dns_type | default('none set') }}"

- name: Setup SSL for the code-server container
  ansible.builtin.include_tasks: "dns.yml"
  when:
    - dns_type is defined
    - dns_type != "none"

- name: Setup vscode for web browser access
  ansible.builtin.include_tasks: "codeserver.yml"

- name: Restart code-server
  ansible.builtin.systemd:
    name: "code-server@{{ username }}"
    enabled: true
    state: restarted
