---
- name: Common workshop setup for control node
  ansible.builtin.include_tasks: 20_workshop_setup.yml

- name: Make sure password is set on Automation controller
  ansible.builtin.include_tasks: "35_controller_pre_build.yml"
  when:
    - controllerinstall is defined
    - controllerinstall|bool

- name: Setup Route53 update service
  ansible.builtin.include_tasks: 40_route53_update.yml
  when: tower_node_aws_api_access | default(false)  | bool
