---
- name: Remove dns entries for each tower node
  ansible.builtin.include_tasks: teardown.yml
  when: teardown|bool

- name: check to see if SSL cert already applied
  uri:
    url: "https://{{ student }}.{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}:{{ public_port | default('443') }}/api/v2/ping/"
    method: GET
    user: admin
    password: "{{ admin_password }}"
    validate_certs: true
    force_basic_auth: true
  register: check_cert
  ignore_errors: true
  failed_when: false
  when:
    - not teardown

- name: Create DNS entries for Automation Controller and SSL cert
  when:
    - not teardown
    - check_cert.status != 200
  block:
    - name: Create DNS entries for each Ansible control node
      ansible.builtin.include_tasks: create.yml

    - name: Configure SSL cert for Automation Controller
      vars:
        dns_name: "{{ student }}.{{ ec2_name_prefix | lower }}.{{ workshop_dns_zone }}"
      ansible.builtin.include_role:
        name: "{{ playbook_dir |dirname }}/roles/issue_cert"

    - name: Wait for Automation Controller to be up
      ansible.builtin.uri:
        url: https://localhost:{{ public_port | default('443') }}/api/controller/v2/ping/
        method: GET
        user: admin
        password: "{{ admin_password }}"
        validate_certs: false
      register: check_controller
      until: check_controller.json is defined and check_controller.json.instances[0].capacity > 0 and check_controller.json.instance_groups[0].capacity > 0
