---
- name: Check if aap.tar.gz exists
  ansible.builtin.debug:
    msg: "{{ playbook_dir }}/aap.tar.gz"

- name: Check if aap.tar.gz exists with stat module
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/aap.tar.gz"
    checksum_algorithm: sha256
  register: stat_var

# - name: Check if aap.tar.gz exists with stat module for symbolic link
#   ansible.builtin.stat:
#     path: "{{ stat_var.stat.lnk_source }}"
#     checksum_algorithm: sha256
#   register: stat_var
#   when: stat_var.stat.checksum is undefined

- name: Print out stat_var
  ansible.builtin.debug:
    msg: "stat_var: {{ stat_var }}"

- name: Print out stat_var.stat.checksum
  ansible.builtin.debug:
    msg:
      - "stat_var: {{ stat_var.stat.checksum }}"
      - "provided_sha_value: {{ provided_sha_value }}"

- name: Check if we have a match
  block:
    - name: Assert we have a match for local tar.gz file
      ansible.builtin.assert:
        that:
          - provided_sha_value == stat_var.stat.checksum

    - name: Assert we have a match for local tar.gz file
      ansible.builtin.debug:
        msg: "success, provided_sha_value == stat_var.stat.checksum"

  rescue:
    - name: No match on local file
      ansible.builtin.debug:
        msg: "No match for aap.tar.gz, going to try downloading"

    - name: Download aap.tar.gz from specified URL
      when: aap_download_url is defined
      ansible.builtin.include_tasks: 09_download_url.yml

    - name: Download aap.tar.gz from access.redhat.com
      ansible.builtin.include_tasks: 10_download.yml
      when: aap_download_url is not defined

    - name: Check if aap.tar.gz again (post download)
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/aap.tar.gz"
        checksum_algorithm: sha256
      register: stat_var

  # - name: Check if aap.tar.gz exists with stat module for symbolic link
  #   ansible.builtin.stat:
  #     path: "{{ stat_var.stat.lnk_source }}"
  #     checksum_algorithm: sha256
  #   register: stat_var
  #   when: stat_var.stat.checksum is undefined

    - name: Verify sha256sum of aap.tar.gz
      ansible.builtin.fail:
        msg: "Failure, sha256sum does not match"
      when: provided_sha_value != stat_var.stat.checksum