---
- name: Install EPEL
  ansible.builtin.dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
    state: present
    disable_gpg_check: true

# Sean March 2, 2022 - not sure we need this if we have EPEL
- name: Setup repo
  ansible.builtin.copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: Configure selinux bindings RHEL8
  ansible.builtin.package:
    name:
      - policycoreutils-python-utils
      - python3-libselinux
    state: present
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
    - ansible_distribution_major_version|int == 8

- name: Install MySQL, PHP, Git
  ansible.builtin.dnf:
    name:
      - mariadb-server
      - php
      - php-fpm
      - php-mysqlnd
      - php-pdo
      - python3
      - git
      - rsync
      - certbot
      - nginx
      - python3-pip
    state: present
