---
- name: workshop_attendance | Create DNS record
  become: false
  amazon.aws.route53:
    state: "{{ s3_state }}"
    zone: "{{ workshop_dns_zone }}"
    record: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    type: A
    overwrite: true
    value: "{{ ansible_host }}"
    wait: true
  delegate_to: localhost
  connection: local
  register: route53_status
  run_once: true
  when:
    - dns_type is defined
    - dns_type == "aws"

- name: set information for instructor
  ansible.builtin.set_fact:
    login_website_information: "Auto-Assignment website located at http://{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone|lower }}, instructor can see workbench assignments at http://{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone|lower }}/list.php"
  delegate_to: localhost
  connection: local
  run_once: true
